os: Visual Studio 2022

environment:
  matrix:
    - arch: x64
      compiler: msvc2019

platform:
  - x64

install:
  # Set paths to dependencies (based on architecture)
  - cmd: set PYTHON_ROOT=C:\python312-x64
  - cmd: set QT_ROOT=C:\Qt\6.5\%compiler%_64
  # Print out dependency paths
  - cmd: echo Using Python at %PYTHON_ROOT%
  - cmd: echo Using Qt at %QT_ROOT%
  # Add necessary paths to PATH variable
  - cmd: set PATH=%cd%;%QT_ROOT%\bin;%PYTHON_ROOT%;%PYTHON_ROOT%\Scripts;%PATH%
  # Install ninja and meson
  - cmd: pip install ninja meson
  # Set up the build environment
  - cmd: if %compiler%==msvc2019 ( call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" %arch% )

build_script:
  - cmd: echo Building on %arch% with %compiler%
  - cmd: meson setup --backend=ninja -Dbuildtype=release -Ddefault_library=static -Ddemo=true builddir
  - cmd: meson compile -C builddir

after_build:
  # Zip build binaries and dependencies
  - cmd: 7z a libopenrazer_%compiler%_%arch%.zip %APPVEYOR_BUILD_FOLDER%\builddir\libopenrazerdemo.exe %QT_ROOT%\bin\Qt6Core.dll %QT_ROOT%\bin\Qt6DBus.dll %QT_ROOT%\bin\Qt6Xml.dll

artifacts:
  - path: libopenrazer*.zip

notifications:
  - provider: Slack
    incoming_webhook: https://webhooks.t2bot.io/api/v1/matrix/hook/gEsoLVFFgp4PURc6iR8IhdQAFhOslmSzfy35y4DEtGL0a5QKIXPIGKUFaJsWkJ7F
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
